### ISSUE TITLE
Enable the `deny(unsafe_op_in_unsafe_fn)` lint everywhere in zcash-light-client-ffi we define `unsafe` functions

### ISSUE THREAD

**Issue by daira** [zcash-hackworks/zcash-light-client-ffi#65]
From https://github.com/zcash-hackworks/zcash-light-client-ffi/pull/32/files#r1022962018 :

A side-effect of declaring a function `unsafe` is that unsafe operations in its body are no longer required to be in `unsafe` blocks (see [Rust RFC 2585](https://rust-lang.github.io/rfcs/2585-unsafe-block-in-unsafe-fn.html) for a proposal to change this, not yet adopted). Ideally, we should enable the `deny(unsafe_op_in_unsafe_fn)` lint everywhere we define `unsafe` functions, since the style we write FFI functions in is mostly already consistent with that lint.

**Comment by daira** [comment]
This can be enabled crate-wide by adding
```
[build]
rustflags = ["-Dunsafe_op_in_unsafe_fn"]
```
in `.cargo/config`.

**Comment by sellout** [comment]
This should also update all `extern` functions to `unsafe extern`.

**Comment by nuttycom** [comment]
I mentioned this in a comment, but has @str4d chimed in on this change yet? He had suggested to me that he preferred that the function *not* be labeled unsafe, but instead that the unsafe operations be explicitly demarcated by unsafe blocks internal to the function, so that it's easier to identify which parts are actually performing unsafe operations.

**Comment by sellout** [comment]
Yeah, that’s the primary portion of this issue – using `deny(unsafe_op_in_unsafe_fn)` so that we can have _both_.

And get back to vacation!

**Comment by daira** [comment]
This will be fixed by #66 (which includes #67).
